GET https://bootcamp-api.codeit.kr/api/0-1/the-julge/shops/4490151c-5217-4157-b072-9c37b05bed47/notices/99996477-82db-4bda-aae1-4044f11d9a8b

###

GET https://bootcamp-api.codeit.kr/api/0-1/the-julge/users/5153a38b-d6f8-471e-b712-fa4f6ae9646d/applications?offset=0&limit=3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MTUzYTM4Yi1kNmY4LTQ3MWUtYjcxMi1mYTRmNmFlOTY0NmQiLCJpYXQiOjE3MTM1OTg4NjN9.U5eutI8_3hI6KzUEFdaV1OpZzUXTNOlxj2QTf3picUw

###

POST https://bootcamp-api.codeit.kr/api/04-10/the-julge/users
Content-Type: application/json

{
  "email": "string",
  "password": "string",
  "type": "employee"
}

###
POST https://bootcamp-api.codeit.kr/api/0-1/the-julge/token
Content-Type: application/json

{
  "email": "wowm@vldksh.com",
  "password": "wowmvldksh1"
}