import type { Metadata } from 'next';
import styles from './page.module.scss';
import './globals.scss';
import Footer from '../components/layout/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={styles.body}>
        <main className={styles.layout}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
