import type { Metadata } from 'next';
import styles from './page.module.scss';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={styles.layout}>{children}</body>
    </html>
  );
}
